[build]
  publish = "build"
  command = "CI=false npm run build"

[dev]
  command = "npm run dev"
  port = 3000
  targetPort = 3001

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API用のプロキシ設定（必要な場合）
# [[redirects]]
#   from = "/api/*"
#   to = "https://your-api-server.example.com/api/:splat"
#   status = 200
#   force = true

[build.environment]
  # 必要な環境変数を設定（APIのURL等）
  REACT_APP_API_URL = ""
  # ビルド時の警告を無視
  CI = "false"

[context.production.environment]
  # 本番環境での環境変数設定
  NODE_ENV = "production" 